name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: denoland/setup-deno@v1
      - run: deno fmt --check
      - run: npm install
      - run: npm test
